import React, { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '../../services/api';
import { Activity } from '@/types';
import { useAuth } from '@/context/AuthContext';
import {
  ClockIcon,
  UserIcon,
  ShieldCheckIcon,
  EyeIcon,
  FunnelIcon,
  InformationCircleIcon
} from '@heroicons/react/24/outline';

export const ActivityLog = () => {
  const [activities, setActivities] = useState<Activity[]>([]);
  const [loading, setLoading] = useState(true);
  const [userFilter, setUserFilter] = useState<string>('');
  const [actionFilter, setActionFilter] = useState<string>('');
  const [msg, setMsg] = useState<{ type: 'success' | 'error', text: string } | null>(null);
  const [isDemoData, setIsDemoData] = useState(false);
  const { user } = useAuth();

  const [searchParams] = useSearchParams();
  const userId = searchParams.get('userId'); // Optional user ID filter from URL

  const loadActivities = async () => {
    setLoading(true);
    try {
      const activityLog = await api.getActivityLog(userId || undefined);
      if (activityLog.length === 0) {
        // Use demo data if empty to show functionality
        setActivities(DEMO_ACTIVITIES);
        setIsDemoData(true);
      } else {
        setActivities(activityLog);
        setIsDemoData(false);
      }
    } catch (error: any) {
      console.error("Failed to load activities", error);
      // Fallback to demo data on error so UI doesn't look "broken"
      setActivities(DEMO_ACTIVITIES);
      setIsDemoData(true);
      if (error.code === 404 || error.message?.includes('collection_not_found')) {
        showNotification('Activity collection ID not found. Using demo data.', 'error');
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadActivities();
  }, [userId]);

  const showNotification = (text: string, type: 'success' | 'error') => {
    setMsg({ text, type });
    setTimeout(() => setMsg(null), 4000);
  };

  const handleCreateTestActivity = async () => {
    if (!user) return;
    try {
      await api.logActivity({
        userId: user.$id,
        userName: user.name,
        userEmail: user.email,
        action: 'other',
        description: 'Manual test activity generated by Admin',
        timestamp: new Date().toISOString(),
        details: { testing: true, browser: navigator.userAgent }
      });
      showNotification('Real test activity logged successfully!', 'success');
      loadActivities();
    } catch (error) {
      showNotification('Failed to save to database. Check your collection ID.', 'error');
    }
  };

  const getActionIcon = (action: string) => {
    switch (action) {
      case 'login':
        return <UserIcon className="h-4 w-4 text-green-600" />;
      case 'logout':
        return <UserIcon className="h-4 w-4 text-gray-600" />;
      case 'submit_price':
        return <ShieldCheckIcon className="h-4 w-4 text-blue-600" />;
      case 'edit_profile':
        return <UserIcon className="h-4 w-4 text-orange-600" />;
      default:
        return <ClockIcon className="h-4 w-4 text-gray-600" />;
    }
  };

  const getActionBadgeColor = (action: string) => {
    switch (action) {
      case 'login':
        return 'bg-green-100 text-green-800';
      case 'logout':
        return 'bg-gray-100 text-gray-800';
      case 'submit_price':
        return 'bg-blue-100 text-blue-800';
      case 'edit_profile':
        return 'bg-orange-100 text-orange-800';
      default:
        return 'bg-purple-100 text-purple-800';
    }
  };

  const filteredActivities = activities.filter(activity => {
    const matchesUser = !userFilter || activity.userName?.toLowerCase().includes(userFilter.toLowerCase()) ||
                       activity.userEmail?.toLowerCase().includes(userFilter.toLowerCase());
    const matchesAction = !actionFilter || activity.action === actionFilter;
    return matchesUser && matchesAction;
  });

  const uniqueActions = Array.from(new Set(activities.map(a => a.action)));

  if (loading) return (
    <div className="flex justify-center items-center h-64">
      <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-indigo-600"></div>
    </div>
  );

  return (
    <div className="space-y-8 animate-fade-in">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Activity Log</h1>
          <p className="mt-1 text-sm text-gray-500">
            {userId ? 'View activities for specific user' : 'Monitor all user activities and system events'}
          </p>
        </div>
        <div className="flex items-center space-x-3">
          <button
            onClick={handleCreateTestActivity}
            className="inline-flex items-center px-4 py-2 bg-indigo-600 text-white text-sm font-bold rounded-lg shadow-md hover:bg-indigo-700 transition-all"
          >
            Create Test Entry
          </button>
          {msg && (
            <div className={`px-4 py-2 rounded-lg text-sm font-bold shadow-sm ${msg.type === 'success' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'} animate-fade-in`}>
              {msg.text}
            </div>
          )}
        </div>
      </div>

      {isDemoData && (
        <div className="bg-amber-50 border-l-4 border-amber-400 p-4 rounded-r-xl shadow-sm">
          <div className="flex items-center">
            <InformationCircleIcon className="h-5 w-5 text-amber-400 mr-3" />
            <p className="text-sm text-amber-700">
              <span className="font-bold">Mode: Demo</span> Currently showing simulated logs. Configure your Appwrite collection ID to see live data.
            </p>
          </div>
        </div>
      )}

      {/* Filters */}
      <div className="bg-white shadow-sm rounded-2xl overflow-hidden border border-gray-200">
        <div className="px-6 py-4 bg-gray-50 border-b border-gray-100 flex items-center">
          <FunnelIcon className="h-5 w-5 text-gray-600 mr-2" />
          <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider">Filter Results</h3>
        </div>
        <div className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label htmlFor="userFilter" className="block text-xs font-bold text-gray-500 uppercase mb-2">User (Name/Email)</label>
              <input
                type="text"
                id="userFilter"
                placeholder="Search users..."
                value={userFilter}
                onChange={(e) => setUserFilter(e.target.value)}
                className="block w-full border-gray-300 rounded-xl shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm p-3 border"
              />
            </div>
            <div>
              <label htmlFor="actionFilter" className="block text-xs font-bold text-gray-500 uppercase mb-2">Action Type</label>
              <select
                id="actionFilter"
                value={actionFilter}
                onChange={(e) => setActionFilter(e.target.value)}
                className="block w-full border-gray-300 rounded-xl shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm p-3 border"
              >
                <option value="">All Activities</option>
                {uniqueActions.map(action => (
                  <option key={action} value={action}>
                    {action.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}
                  </option>
                ))}
              </select>
            </div>
          </div>
        </div>
      </div>

      {/* Activity Log */}
      <div className="bg-white shadow-sm rounded-2xl overflow-hidden border border-gray-200">
        <div className="px-6 py-4 bg-indigo-50 border-b border-indigo-100 flex justify-between items-center">
          <div className="flex items-center">
            <ClockIcon className="h-5 w-5 text-indigo-600 mr-2" />
            <h3 className="text-sm font-bold text-indigo-900 uppercase tracking-wider">Activity History</h3>
          </div>
          <span className="bg-indigo-100 text-indigo-700 px-3 py-1 rounded-full text-xs font-bold">
            {filteredActivities.length} {filteredActivities.length === 1 ? 'entry' : 'entries'}
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">User</th>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Action</th>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Description</th>
                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 uppercase">Timestamp</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {filteredActivities.map((activity) => (
                <tr key={activity.$id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="h-9 w-9 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 font-bold">
                        {activity.userName?.charAt(0) || <UserIcon className="h-5 w-5" />}
                      </div>
                      <div className="ml-3">
                        <div className="text-sm font-bold text-gray-900">{activity.userName || 'Unknown User'}</div>
                        <div className="text-xs text-gray-500">{activity.userEmail}</div>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-bold ${getActionBadgeColor(activity.action)}`}>
                      {getActionIcon(activity.action)}
                      <span className="ml-1.5 capitalize">{activity.action.replace('_', ' ')}</span>
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="text-sm text-gray-700 max-w-md" title={activity.description}>
                      {activity.description}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {activity.timestamp ? new Date(activity.timestamp).toLocaleString() : 'Unknown'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {filteredActivities.length === 0 && (
          <div className="px-6 py-20 text-center">
            <ClockIcon className="mx-auto h-12 w-12 text-gray-300" />
            <h3 className="mt-4 text-lg font-bold text-gray-900">No activities found</h3>
            <p className="text-gray-500 mt-1">Try adjusting your filters or create a test entry.</p>
          </div>
        )}
      </div>
    </div>
  );
};

const DEMO_ACTIVITIES: Activity[] = [
  {
    $id: 'demo-1',
    userId: 'u1',
    userName: 'Admin User',
    userEmail: 'admin@marketcheck.com',
    action: 'login',
    description: 'System administrator logged in to dashboard',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    details: { role: 'admin', ip: '127.0.0.1' }
  },
  {
    $id: 'demo-2',
    userId: 'u2',
    userName: 'Sanni Abdullahi',
    userEmail: 'sanni@grains.com',
    action: 'submit_price',
    description: 'Updated Maize price in Bodija Market',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    details: { market: 'Bodija', price: 45000, commodity: 'Maize' }
  },
  {
    $id: 'demo-3',
    userId: 'u3',
    userName: 'Janet Oke',
    userEmail: 'janet@traders.ng',
    action: 'edit_profile',
    description: 'User updated their trader profile information',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  }
];